### ISSUE TITLE
Taint Issue in Wrath

### ISSUE THREAD

**Issue by Gogo1951** [KyrosKrane/AnnoyingPopupRemover#13]
Could be something else, but the error is attributed to APR.

9/18 19:43:10.473  An action was blocked because of taint from AnnoyingPopupRemover - Search()
9/18 19:43:10.473      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:225 LFGBrowse_DoSearch()
9/18 19:43:10.473      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:178 LFGBrowseFrame:SearchActiveEntry()
9/18 19:43:10.473      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
9/18 19:43:10.473      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:67

**Comment by KyrosKrane** [comment]
This is almost certainly not APR related. It's due to some other addon that shares a common library with APR. The other addon interacts in some way with the quest window or the LFG window, and that's causing the taint. If you try the same actions again with only APR enabled, it won't taint.

If you can give me a complete list of addons you have running, I can double check to be sure, but I'm 99% convinced this isn't an APR issue.

**Comment by Gogo1951** [comment]
Yeah figured. (=

Elv has been buggy AF since updating to their "unified all WoW" version. Guessing it's Elv. Not likely anything you can do. Thanks mate!
