### ISSUE TITLE
Remove "<Addon> has been blocked from an action only available to the Blizzard UI" Pop-up

### ISSUE THREAD

**Issue by creed-us** [KyrosKrane/AnnoyingPopupRemover#40]
Sometimes this shows up when using auto quest add-ons, and there are no alternatives to make this message not show up when using said auto-quest add-ons. They show up each time the add-ons accept a quest and it is rather irritating to have to click it off.
![image](https://github.com/KyrosKrane/AnnoyingPopupRemover/assets/32348022/151707e9-e642-41c0-a3e6-85bdfff065d3)

**Comment by KyrosKrane** [comment]
Unfortunately this popup is due to some questionable code decisions by Blizzard itself; it's not the fault of any one addon. That particular dialog is also protected, so I can't make it go away with APR.

The best I can suggest is to get an addon called [TaintLess](https://www.townlong-yak.com/addons/taintless). It helps reduce the number of times that popup happens, but it may not completely eliminate it. You just install it like any other addon, and it works silently; there's no options to configure or anything.
