### ISSUE TITLE
I HAVE TO CLICK EVERYTIME ! :(

### ISSUE THREAD

**Issue by sasuke1094123** [KyrosKrane/AnnoyingPopupRemover#54]
![image](https://github.com/user-attachments/assets/c76e1dd6-b7dc-449c-af05-3d07ced4bbf2)
by any chance to can u send me this button always checked please i have lot of alts and i got bored to click every time :(

**Comment by KyrosKrane** [comment]
That setting is off by default because it can cause item loss - for example, if you want to list the item on the auction house, you might right click it to put in the AH post window. But if the AH window closes unexpectedly, then the right click would cause the item to be equipped. Now you can't sell the item any more.

That's just one example of course. There are many other cases where this can have unintended results. So, I think it's better to click this setting one time for people who want it, than to make people who don't want it lose their item by mistake.

If you want, you can also change this setting on the command line. Just type this in chat, or add it to a macro:

`/apr equip`

**Comment by sasuke1094123** [comment]
İs it possible to share in here its selected version?

25 Tem 2024 Per 22:47 tarihinde KyrosKrane Sylvanblade <
***@***.***> şunu yazdı:

**Comment by KyrosKrane** [comment]
If you mean can I make a custom version with it always enabled, no. I would have to maintain two versions, which is double the work.

But if you want to change it yourself in your own copy, that's an easy change. 

Open `module_equip.lua` in any text editor, then change line 34 from:
```
this.DBDefaultValue = APR.SHOW_DIALOG
```
to 
```
this.DBDefaultValue = APR.HIDE_DIALOG
```

Then, each time you start using APR with a new toon, it will default to checked. But, if you've already logged into a toon with APR loaded, then you will have to manually check the box for it.

You will have to make this same change any time you update to a newer version. Otherwise the new version will overwrite your change.

**Comment by sasuke1094123** [comment]
U are best addon maker Man tyvm

26 Tem 2024 Cum 01:34 tarihinde KyrosKrane Sylvanblade <
***@***.***> şunu yazdı:
